name: Create Unity Package

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ypicard/get-branch-name-github-action@v1
      id: names

    - run: find Assets/ -name \*.meta > metaList
    - run: mkdir build

    - uses: pCYSl5EDgo/create-unitypackage@master
      with:
        package-path: 'build/InariUdon-${{ steps.names.outputs.tag }}..unitypackage'
        include-files: metaList

    - uses: actions/upload-artifact@master
      with:
        path: build
        name: package
